/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as BecomeTutorRouteImport } from './routes/become-tutor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as VideoCallCallIdRouteImport } from './routes/video-call.$callId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeTutorRoute = BecomeTutorRouteImport.update({
  id: '/become-tutor',
  path: '/become-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoCallCallIdRoute = VideoCallCallIdRouteImport.update({
  id: '/video-call/$callId',
  path: '/video-call/$callId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/become-tutor': typeof BecomeTutorRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tutors': typeof TutorsRoute
  '/video-call/$callId': typeof VideoCallCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/become-tutor': typeof BecomeTutorRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tutors': typeof TutorsRoute
  '/video-call/$callId': typeof VideoCallCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/become-tutor': typeof BecomeTutorRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tutors': typeof TutorsRoute
  '/video-call/$callId': typeof VideoCallCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/admin'
    | '/admin-login'
    | '/become-tutor'
    | '/dashboard'
    | '/explore'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/register'
    | '/settings'
    | '/shop'
    | '/tutors'
    | '/video-call/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/admin'
    | '/admin-login'
    | '/become-tutor'
    | '/dashboard'
    | '/explore'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/register'
    | '/settings'
    | '/shop'
    | '/tutors'
    | '/video-call/$callId'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/admin'
    | '/admin-login'
    | '/become-tutor'
    | '/dashboard'
    | '/explore'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/register'
    | '/settings'
    | '/shop'
    | '/tutors'
    | '/video-call/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BecomeTutorRoute: typeof BecomeTutorRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  TutorsRoute: typeof TutorsRoute
  VideoCallCallIdRoute: typeof VideoCallCallIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-tutor': {
      id: '/become-tutor'
      path: '/become-tutor'
      fullPath: '/become-tutor'
      preLoaderRoute: typeof BecomeTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-call/$callId': {
      id: '/video-call/$callId'
      path: '/video-call/$callId'
      fullPath: '/video-call/$callId'
      preLoaderRoute: typeof VideoCallCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  BecomeTutorRoute: BecomeTutorRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  TutorsRoute: TutorsRoute,
  VideoCallCallIdRoute: VideoCallCallIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
